### ISSUE TITLE
Dynamically create inner schemas derived from spec schemas

### ISSUE THREAD

**Issue by walsha2** [tazatechnology/openapi_spec#17]
#### `CreateCompletionResponse`

The `choices` array is generated as `List<Map<String, dynamic>>` instead of a List of the inner object. 

[`dart-dio`](https://openapi-generator.tech/docs/generators/dart-dio) generator creates a `final List<CreateCompletionResponseChoicesInner> choices` by default. So they concatenate the schema name (`CreateCompletionResponse`), plus the field (`choices`) plus `Inner` to create the class name of the inner object.

_Originally posted by @davidmigloz in https://github.com/tazatechnology/openapi_spec/issues/13#issuecomment-1770441157_

**Comment by walsha2** [comment]
> [`dart-dio`](https://openapi-generator.tech/docs/generators/dart-dio) generator creates a `final List<CreateCompletionResponseChoicesInner> choices` by default.

@davidmigloz Besides unions, the `openapi_spec` generator avoids creating any extra or intermediate classes. So this is not unexpected.

It always bothers me when a spec does not return typed arrays especially when they already do it in other parts of the schema, e.g. `CreateChatCompletionRequest.functions`:

```yaml
functions:
  description: A list of functions the model may generate JSON inputs for.
  type: array
  items:
    $ref: "#/components/schemas/ChatCompletionFunctions"
```

So your proposal is that this generator does indeed create these undefined types and come up with some sort of naming convention, similar to `${field}Inner`? 

Im not opposed to the idea, just providing some background as to why this is not in the code already. If a class schema is not defined in the spec, it is not created.

**Comment by davidmigloz** [comment]
Yeah, it bothers me as well. But, unfortunately, I've seen many specs that do that, so it'd be nice to support it.

I've checked the [java](https://openapi-generator.tech/docs/generators/java) and [go](https://openapi-generator.tech/docs/generators/go) generators and both follow the `${field}Inner` convention as well. If there are several levels of nesting they attach `Inner` for each level, so if there are two levels you would get `${field}InnerInner`.

**Comment by davidmigloz** [comment]
I took a look again at the behaviour of those generators and their logic is:

- If the inner object doesn't have a `title` property, then the `${field}Inner` convention is used

E.g.: 
```yaml
CreateCompletionResponse:
  type: object
  properties:
    choices:
      type: array
      description: The list of completion choices the model generated for the input prompt.
      items:
        type: object
        properties:
          finish_reason:
          ...
```
The generator will generate `CreateCompletionResponseChoicesInner.java`.

- If the inner object has a `title` property, then the title is used

E.g.: 
```yaml
CreateCompletionResponse:
  type: object
  properties:
    choices:
      type: array
      description: The list of completion choices the model generated for the input prompt.
      items:
        type: object
        title: CompletionChoice
        properties:
          finish_reason:
          ...
```

The generator will generate `CompletionChoice.java`.

**Comment by walsha2** [comment]
> If the inner object has a title property, then the title is used

Hmm... how do you ensure that this inner object is unique across all schemas? There is nothing preventing another object from having. It seems that `CompletionChoice` would not be robust enough if solely relying on the inner array item `title` property.

```yaml
AnotherComponent:
  type: object
  properties:
    choices:
      type: array
      description: The list of completion choices the model generated for the input prompt.
      items:
        type: object
        title: CompletionChoice
```
